apiVersion: v1
kind: Namespace
metadata:
  name: pwatcher-test
  annotations:
    pwatcher-test: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: pwatcher-test
  labels:
    role: myrole
  annotations:
    pwatcher-test: "true"
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP