{{- if .Values.rbac.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pwatcher.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pwatcher.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "pwatcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---
{{- if .Values.rbac.allowProxyRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pwatcher.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pwatcher.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "pwatcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

---
{{- if .Values.rbac.allowMetricsReaderRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pwatcher.fullname" . }}-metrics-reader-rolebbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pwatcher.fullname" . }}-metrics-reader
subjects:
- kind: ServiceAccount
  name: {{ include "pwatcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  
{{- end }}
