apiVersion: v1
kind: Service
metadata:
  name: {{ include "pwatcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pwatcher.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      name: https
  selector:
    {{- include "pwatcher.selectorLabels" . | nindent 4 }}